// Install the observe hook into a project's agent harness (Claude Code / Codex) and materialize
// the standalone hook + scanner into ./.insta/observe.
import { copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { alreadyTracked, ensureGitignore } from '../gitignore.js'

const MARKER = 'insta-observe'

// What the hook leaves under ./.insta that is machine-local, not project source: observe/ is a
// copy of this CLI version's hook + scanner (regenerated by every `project link`), and
// audit.jsonl is this machine's findings (fingerprints + redacted context — `insta agent observe sync`
// is the share path). ./.insta/project.json stays committable: it is the team's project binding.
const LOCAL_PATHS = ['.insta/observe/', '.insta/audit.jsonl']
const GITIGNORE_COMMENT = '# InstaCloud: local observe-hook state (regenerated per machine, not source)'
const DEFAULT_ASSET_DIR = dirname(fileURLToPath(import.meta.url)) // built: cli/dist/observe

function cliVersion(): string {
  try { return JSON.parse(readFileSync(join(DEFAULT_ASSET_DIR, '..', '..', 'package.json'), 'utf8')).version ?? '0.0.0' }
  catch { return '0.0.0' }
}

function isInstaHook(h: { _insta?: string; command?: string; args?: string[] }): boolean {
  if (h._insta === MARKER) return true
  const blob = `${h.command ?? ''} ${(h.args ?? []).join(' ')}`
  return blob.includes('observe/hook.') // matches .insta/observe/hook.js; trailing dot avoids matching user paths
}

type Group = { matcher?: string; hooks?: Array<Record<string, unknown>> }

function upsert(root: any, entry: Group): void {
  root.hooks ??= {}
  const post: Group[] = Array.isArray(root.hooks.PostToolUse) ? root.hooks.PostToolUse : []
  for (const g of post) g.hooks = (g.hooks ?? []).filter((h) => !isInstaHook(h))
  const pruned = post.filter((g) => (g.hooks ?? []).length > 0)
  pruned.push(entry)
  root.hooks.PostToolUse = pruned
}

function registerHarness(filePath: string, entry: Group): void {
  const root = existsSync(filePath) ? JSON.parse(readFileSync(filePath, 'utf8')) : {}
  upsert(root, entry)
  mkdirSync(dirname(filePath), { recursive: true })
  writeFileSync(filePath, JSON.stringify(root, null, 2) + '\n')
}

function unregisterHarness(filePath: string): void {
  if (!existsSync(filePath)) return
  const root = JSON.parse(readFileSync(filePath, 'utf8'))
  const post: Group[] | undefined = root?.hooks?.PostToolUse
  if (!Array.isArray(post)) return
  for (const g of post) g.hooks = (g.hooks ?? []).filter((h) => !isInstaHook(h))
  root.hooks.PostToolUse = post.filter((g) => (g.hooks ?? []).length > 0)
  writeFileSync(filePath, JSON.stringify(root, null, 2) + '\n')
}

function materialize(cwd: string, assetDir: string): void {
  const dest = join(cwd, '.insta', 'observe')
  mkdirSync(dest, { recursive: true })
  copyFileSync(join(assetDir, 'hook.js'), join(dest, 'hook.js'))     // throws if assets missing (e.g. not built)
  copyFileSync(join(assetDir, 'scanner.js'), join(dest, 'scanner.js'))
  writeFileSync(join(dest, 'package.json'), JSON.stringify({ type: 'module' }, null, 2) + '\n') // run .js as ESM
  writeFileSync(join(dest, 'VERSION'), cliVersion() + '\n')
}

function claudeEntry(): Group {
  // Claude Code executes `command` as ONE shell string with $CLAUDE_PROJECT_DIR in the env —
  // there is no `args` field in its hooks schema, so a ${…} template in args reaches node
  // verbatim and throws MODULE_NOT_FOUND after every tool call.
  // .claude/settings.json is often committed while ./.insta stays local-only, so a fresh
  // clone (cloud session, teammate) gets the hook without the script — no-op there.
  const hook = '"$CLAUDE_PROJECT_DIR/.insta/observe/hook.js"'
  return { matcher: '*', hooks: [{ type: 'command',
    command: `[ ! -f ${hook} ] || node ${hook}`, timeout: 15, _insta: MARKER }] }
}
// The Codex hook command. Constraints that rule out every simpler form:
//  - no absolute path: it made .codex/hooks.json machine-specific (a teammate committing it shipped
//    /Users/<author>/… to every clone, where node failed after each tool call);
//  - not `git rev-parse --show-toplevel`: the insta project root is wherever `project link` ran,
//    which in a monorepo is below the git root (`findProjectRoot` climbs for .insta/project.json
//    for exactly that reason), so the hook would silently never fire there;
//  - no POSIX shell syntax: with no `commandWindows` override Codex hands `command` verbatim to
//    cmd.exe on Windows, where `[ ! -f … ]` / `$(…)` are parse errors — after every tool call.
// So: one shell-neutral `node -e` that climbs from the session cwd (Codex runs project hooks with
// the project as cwd) to the nearest .insta/observe/hook.js and runs it with stdin passed through;
// a fresh clone with no ./.insta anywhere above is a silent no-op. The script must stay free of
// characters either shell rewrites inside double quotes: `$` and backticks (sh), `%` and `!`
// (cmd.exe), and `"` (both). Codex has each user trust the entry before it runs, so shareable is safe.
// Exit code: the hook's own status when it ran; 0 when it could not be started or was killed
// (status null) — every other arm of this install is silent best-effort, and Codex reports any
// non-zero exit as a failed hook after EVERY tool call, which is worse than a missed audit line.
const CODEX_HOOK_SCRIPT = [
  "const f=require('fs'),p=require('path'),c=require('child_process');",
  'let d=process.cwd();',
  'for(;;){',
  "const h=p.join(d,'.insta/observe/hook.js');",
  "if(f.existsSync(h)){const r=c.spawnSync(process.execPath,[h],{stdio:'inherit'});process.exitCode=r.status===null?0:r.status;break}",
  'const u=p.dirname(d);if(u===d)break;d=u}',
].join('')

function codexEntry(): Group {
  return { matcher: '*', hooks: [{ type: 'command',
    command: `node -e "${CODEX_HOOK_SCRIPT}"`, timeout: 15, _insta: MARKER }] }
}

export type ObserveInstall = {
  claude: boolean
  codex: boolean
  /** .gitignore entries added by this call (empty on a re-link). */
  ignored: string[]
  /** LOCAL_PATHS entries git already tracks — an ignore entry can't help those; see `untrackHint`. */
  tracked: string[]
}

export function installObserve(opts: { cwd: string; assetDir?: string }): ObserveInstall {
  materialize(opts.cwd, opts.assetDir ?? DEFAULT_ASSET_DIR) // hook required → let a missing asset throw to the caller
  // Ignore the local state in the same step that creates it, so nobody discovers it via
  // `git status`. Best-effort: an unwritable .gitignore must not fail the hook install.
  // (Uninstall deliberately leaves the entries: a stale audit.jsonl should stay ignored.)
  let ignored: string[] = []
  try { ignored = ensureGitignore(opts.cwd, LOCAL_PATHS, GITIGNORE_COMMENT) } catch { /* keep going */ }
  const tracked = alreadyTracked(opts.cwd, LOCAL_PATHS)
  let claude = false
  let codex = false
  try { registerHarness(join(opts.cwd, '.claude', 'settings.json'), claudeEntry()); claude = true } catch { /* skip malformed */ }
  try { registerHarness(join(opts.cwd, '.codex', 'hooks.json'), codexEntry()); codex = true } catch { /* skip malformed */ }
  return { claude, codex, ignored, tracked }
}

export function uninstallObserve(cwd: string): void {
  try { unregisterHarness(join(cwd, '.claude', 'settings.json')) } catch { /* skip */ }
  try { unregisterHarness(join(cwd, '.codex', 'hooks.json')) } catch { /* skip */ }
}
