// Build a source directory into an image and push it to Fly's registry, using a short-lived,
// app-scoped deploy token minted by the platform (the CLI never holds a standing Fly credential).
// Shells out to `flyctl deploy --build-only --push` (remote builder).
import { spawn } from 'node:child_process'
import { existsSync, writeFileSync, unlinkSync } from 'node:fs'
import { join } from 'node:path'

export type BuildRunner = (
  cmd: string,
  args: string[],
  opts: { cwd: string; env: Record<string, string> },
) => Promise<{ code: number; output: string }>

// Spawn flyctl, tee its output to the user (so they see buildkit progress) AND capture it for digest
// parsing. `to` picks the tee destination for the child's stdout: `deploy --json` reserves the
// process's stdout for the final JSON document, so it tees build progress to stderr instead.
function teeRunner(to: NodeJS.WriteStream): BuildRunner {
  return (cmd, args, opts) =>
    new Promise((resolve) => {
      const child = spawn(cmd, args, { cwd: opts.cwd, env: opts.env, stdio: ['inherit', 'pipe', 'pipe'] })
      let output = ''
      child.stdout?.on('data', (b) => { const s = b.toString(); output += s; to.write(s) })
      child.stderr?.on('data', (b) => { const s = b.toString(); output += s; process.stderr.write(s) })
      child.on('error', (err) => resolve({ code: -1, output: `${output}\n${err.message}` }))
      child.on('close', (code) => resolve({ code: code ?? -1, output }))
    })
}
export const defaultBuildRunner: BuildRunner = teeRunner(process.stdout)
export const stderrBuildRunner: BuildRunner = teeRunner(process.stderr)

// buildkit prints "pushing manifest for registry.fly.io/<app>:<label>@sha256:<digest>" on push.
// Pin to the digest — the bare tag races on Fly's registry (MANIFEST_UNKNOWN); the digest always resolves.
export function parseImageDigest(output: string, flyApp: string): string | null {
  const m = output.match(/pushing manifest for registry\.fly\.io\/[^\s]+@(sha256:[0-9a-f]+)/)
  return m ? `registry.fly.io/${flyApp}@${m[1]}` : null
}

// Write a minimal stub fly.toml iff the dir has none (flyctl needs app config; a fresh app has no
// machines to derive it from). Region is build-config only — `--build-only` places no machines.
// Returns a cleanup callback the caller MUST run in finally; leaves a user's own fly.toml alone.
function ensureFlyTomlStub(dir: string, flyApp: string, port: number): () => void {
  const path = join(dir, 'fly.toml')
  if (existsSync(path)) return () => { /* user owns it */ }
  const stub =
    `# Auto-generated by insta for source deploy. Safe to delete.\n` +
    `app = "${flyApp}"\n` +
    `primary_region = "iad"\n\n` +
    `[build]\n\n` +
    `[http_service]\n` +
    `  internal_port = ${port}\n` +
    `  force_https = true\n`
  writeFileSync(path, stub, 'utf8')
  return () => { try { unlinkSync(path) } catch { /* best-effort */ } }
}

export async function flyctlBuildAndPush(
  opts: { dir: string; flyApp: string; imageLabel: string; token: string; port: number },
  run: BuildRunner = defaultBuildRunner,
): Promise<{ imageRef: string }> {
  const cleanup = ensureFlyTomlStub(opts.dir, opts.flyApp, opts.port)
  try {
    const { code, output } = await run(
      'flyctl',
      ['deploy', '--remote-only', '--build-only', '--push', '--app', opts.flyApp, '--image-label', opts.imageLabel, '--no-cache'],
      { cwd: opts.dir, env: { ...process.env, FLY_API_TOKEN: opts.token } as Record<string, string> },
    )
    if (code !== 0) throw new Error(`flyctl deploy --build-only failed (exit ${code}). See output above.`)
    const imageRef = parseImageDigest(output, opts.flyApp)
    if (!imageRef) throw new Error('flyctl build succeeded but no "pushing manifest" digest line was found — cannot determine the image. Re-run with FLY_LOG_LEVEL=debug.')
    return { imageRef }
  } finally {
    cleanup()
  }
}

// Best-effort: ensure the fly CLI is available (needed for source-directory deploys). Never blocks —
// if it can't be installed the subsequent build surfaces a clear error. Everything here is one-time
// bootstrap DIAGNOSTICS, so it all goes to stderr — including the installers' own stdout (fd 2 in
// the stdio triple) — keeping stdout clean for `deploy --json`.
export async function ensureFlyctl(): Promise<void> {
  const note = (m: string) => process.stderr.write(m + '\n')
  const ok = (cmd: string, args: string[], inherit = false) =>
    new Promise<boolean>((resolve) => {
      const p = spawn(cmd, args, { stdio: inherit ? ['inherit', 2, 2] : 'ignore' })
      p.on('error', () => resolve(false))
      p.on('close', (code) => resolve(code === 0))
    })
  try {
    if (await ok('flyctl', ['version'])) return
    if (process.platform === 'darwin' && (await ok('brew', ['--version']))) {
      note('flyctl not found — installing with `brew install flyctl` (one-time)…')
      note((await ok('brew', ['install', 'flyctl'], true)) ? 'flyctl installed ✓' : 'flyctl install failed — install manually: https://fly.io/docs/flyctl/install/')
      return
    }
    if (process.platform === 'linux') {
      // A fresh Linux machine (CI containers included) has no flyctl
      // and no brew; without this branch `insta deploy <dir>` dead-ends on a hand-install of a
      // third-party CLI. Official installer, pinned into ~/.fly; the current process extends its
      // own PATH because the installer's shell-profile edit can't reach an already-running process.
      note('flyctl not found — installing to ~/.fly (one-time)…')
      const flyHome = `${process.env.HOME ?? '~'}/.fly`
      const installed = await ok('sh', ['-c', `curl -fsSL https://fly.io/install.sh | FLYCTL_INSTALL="${flyHome}" sh`], true)
      if (installed) {
        process.env.PATH = `${process.env.PATH}:${flyHome}/bin`
        if (await ok('flyctl', ['version'])) { note('flyctl installed ✓'); return }
      }
      note('flyctl install failed — install manually: https://fly.io/docs/flyctl/install/')
      return
    }
    note('flyctl (fly CLI) not found — install it to deploy from source: https://fly.io/docs/flyctl/install/')
  } catch { /* best-effort convenience */ }
}
